export const GET_VOLUNTEERS = "GET_VOLUNTEERS",
    STORE_PERSONAL_INFORMATION = "STORE_PERSONAL_INFORMATION",
    STORE_CONTRIBUTION_INFORMATION = "STORE_CONTRIBUTION_INFORMATION",
    STORE_RESUME_INFORMATION = "STORE_RESUME_INFORMATION",
    STORE_SCREENING_INFROMATION = "STORE_SCREENING_INFROMATION";
