export const GET_VOLUNTEERS = "GET_VOLUNTEERS",
    STORE_PERSONAL_INFORMATION = "STORE_PERSONAL_INFORMATION",
    STORE_EXPERIENCE_INFORMATION = "STORE_EXPERIENCE_INFORMATION",
    STORE_REFERENCE_INFORMATION = "STORE_REFERENCE_INFORMATION",
    STORE_SCREENING_INFROMATION = "STORE_SCREENING_INFROMATION";
