export const GET_DETAILS = "GET_DETAILS",
  SET_OUR_FOCUS = "SET_OUR_FOCUS",
  GET_OUR_FOCUS = "GET_OUR_FOCUS",
  LOGON_VERIFY_USER_AUTHENTICATED_STATUS_ERROR =
    "LOGON_VERIFY_USER_AUTHENTICATED_STATUS_ERROR";
